name: 'Tag-Push Action'
description: 'Retag and push multiplatform docker images'
author: 'Akhil Mohan'
inputs:
  src:
    required: true
    description: 'Source tag'
  dst:
    required: true
    description: 'Destination tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
